version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: sad_postgres
    hostname: sad_postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=saddb
  backend:
    image: openjdk:17
    container_name: sad_backend
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./target/sadbe-0.1.jar:/opt/app.jar
    command: java -jar -Ddb.url=jdbc:postgresql://sad_postgres:5432/saddb /opt/app.jar