version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: sad_postgres
    hostname: sad_postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    networks:
      - network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=saddb
  backend:
    image: openjdk:17
    container_name: sad_backend
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - network
    volumes:
      - ./target/SADbe-0.1.jar:/opt/app.jar
    command: java -jar -Ddb.url=jdbc:postgresql://sad_postgres:5432/saddb /opt/app.jar
  front:
    image: nginx:stable-alpine
    container_name: sad_frontend
    expose:
      - 80
    ports:
      - 8081:80
    networks:
      - network
    volumes:
      - ./front/dist:/usr/share/nginx/html
    command: nginx -g "daemon off;"

networks:
  network:
    driver: bridge
    name: bridge_net
